CREATE TABLE IF NOT EXISTS source_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,
  source_category TEXT NOT NULL,
  external_id TEXT NOT NULL,
  source_url TEXT NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL,
  published_at TIMESTAMPTZ,
  university_name TEXT,
  title TEXT NOT NULL,
  author TEXT,
  raw_text TEXT NOT NULL,
  document_id TEXT,
  policy_status TEXT,
  financial_cost DOUBLE PRECISION,
  funding_source TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_hash TEXT NOT NULL,
  screened_at TIMESTAMPTZ,
  emailed_at TIMESTAMPTZ,
  analysis JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (source, external_id)
);

CREATE INDEX IF NOT EXISTS source_items_pending_idx
  ON source_items (observed_at)
  WHERE screened_at IS NULL;

CREATE TABLE IF NOT EXISTS monitor_runs (
  id UUID PRIMARY KEY,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  status TEXT NOT NULL CHECK (status IN ('running', 'success', 'partial', 'failed')),
  details JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS digest_deliveries (
  idempotency_key TEXT PRIMARY KEY,
  external_ids JSONB NOT NULL,
  provider_id TEXT NOT NULL,
  sent_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inbound_messages (
  email_id TEXT PRIMARY KEY,
  sender TEXT NOT NULL,
  subject TEXT NOT NULL,
  message_id TEXT NOT NULL,
  received_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('processing', 'completed', 'failed')),
  request_text TEXT NOT NULL,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  result JSONB,
  delivery_id TEXT,
  error TEXT,
  attempts INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS inbound_messages_status_idx
  ON inbound_messages (status, received_at);

ALTER TABLE source_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE monitor_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE digest_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE inbound_messages ENABLE ROW LEVEL SECURITY;
